name: Build Android
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install npm dependencies
        run: yarn

      - name: Build Android Debug
        run: cd android && ./gradlew assembleDebug

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
